artifacts_root: artifacts

data_ingestion:
  root_dir: artifcats/data_ingestion
  source_URL: https://drive.google.com/file/d/1EZhldpQaCK_k1pS961yGklKRoSAUdtFJ/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
