artifacts_root: artifacts

data_ingestion: #01
  root_dir: artifcats/data_ingestion
  source_URL: https://drive.google.com/file/d/1EZhldpQaCK_k1pS961yGklKRoSAUdtFJ/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model: # 02 - vgg-16
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5 
  